version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - python -m pip install poetry

    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry run python -c "import tilemapbase; tilemapbase.init(create=True)"

  apt_packages:
    - graphviz
    
sphinx:
  configuration: doc/source/conf.py
